
# SETTINGS
SEG_CONF = 0.8
PLAYER_CONF = 0.25
KEYPOINT_CONF = 0.3
KEYPOINT_MIN_CONF = 0.3
MAX_FRAMES = None
PROCESS_EVERY_N_FRAMES = 1
REUSE_LAST_HOMOGRAPHY = True


# PITCH GEOMETRY
PITCH_LENGTH = 105.0
PITCH_WIDTH = 68.0
CENTER_X = PITCH_LENGTH / 2.0
CENTER_Y = PITCH_WIDTH / 2.0
CENTER_CIRCLE_RADIUS = 9.15
PENALTY_AREA_DEPTH = 16.5
PENALTY_AREA_WIDTH = 40.32
GOAL_AREA_DEPTH = 5.5
GOAL_AREA_WIDTH = 18.32
PENALTY_SPOT_DISTANCE = 11.0
PENALTY_ARC_RADIUS = 9.15
LEFT_PENALTY_X = PENALTY_AREA_DEPTH
RIGHT_PENALTY_X = PITCH_LENGTH - PENALTY_AREA_DEPTH
LEFT_GOAL_AREA_X = GOAL_AREA_DEPTH
RIGHT_GOAL_AREA_X = PITCH_LENGTH - GOAL_AREA_DEPTH
PENALTY_Y_TOP = (PITCH_WIDTH - PENALTY_AREA_WIDTH) / 2.0
PENALTY_Y_BOTTOM = (PITCH_WIDTH + PENALTY_AREA_WIDTH) / 2.0
GOAL_AREA_Y_TOP = (PITCH_WIDTH - GOAL_AREA_WIDTH) / 2.0
GOAL_AREA_Y_BOTTOM = (PITCH_WIDTH + GOAL_AREA_WIDTH) / 2.0
LEFT_PENALTY_SPOT_X = PENALTY_SPOT_DISTANCE
RIGHT_PENALTY_SPOT_X = PITCH_LENGTH - PENALTY_SPOT_DISTANCE

# CANVAS SETTINGS

DRAW_SCALE = 14 # Convert pixels into a bigger visual dot(s)
BORDER = 80

CANVAS_W = int(PITCH_LENGTH * DRAW_SCALE + 2 * BORDER)
CANVAS_H = int(PITCH_WIDTH * DRAW_SCALE + 2 * BORDER)


# PITCH COLORS 
GREEN=(34, 139, 34)
WHITE=(255, 255, 255)
WHITE_LINE_THICKNESS=2

# SegmentationPriority 
SEGMENTATION_PRIORITY = {
    "18Yard": 140,
    "5Yard": 170,
    "Half Central Circle": 200,
    "18Yard Circle": 100,
    "Half Field": 20,
}